"""Render an engagement into HTML / PDF / DOCX.

One inline Jinja2 template drives HTML; xhtml2pdf turns that same HTML into PDF (pure-Python, no
native GTK deps — WeasyPrint needs system libs that don't ship on Windows). DOCX is built directly
with python-docx. Sections: title, scope + authorization statement, methodology, findings by
severity with CWE/CVE/ATT&CK/remediation, retest checklist, appendix.
"""
from __future__ import annotations

import io
from typing import Optional

from jinja2 import Template

_SEV_ORDER = ["critical", "high", "medium", "low", "info"]
_SEV_COLOR = {"critical": "#b00020", "high": "#d84315", "medium": "#f9a825",
              "low": "#2e7d32", "info": "#546e7a"}

_HTML = Template("""<!doctype html>
<html><head><meta charset="utf-8"><style>
  body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 11px; }
  h1 { color: #0d1b2a; border-bottom: 3px solid #0d1b2a; padding-bottom: 6px; }
  h2 { color: #0d1b2a; margin-top: 22px; border-bottom: 1px solid #ccc; }
  .meta td { padding: 2px 10px 2px 0; }
  .sev { color: #fff; padding: 1px 6px; border-radius: 3px; font-weight: bold; }
  .tiles td { text-align: center; padding: 8px 14px; border: 1px solid #ddd; }
  .tiles .n { font-size: 20px; font-weight: bold; }
  .finding { border: 1px solid #e0e0e0; border-left: 4px solid #999; padding: 8px 12px; margin: 8px 0; }
  .k { color: #666; }
  table { border-collapse: collapse; }
  .muted { color: #777; }
</style></head><body>
  <h1>{{ eng.client }} — Penetration Test Report</h1>
  <table class="meta">
    <tr><td class="k">Engagement</td><td>{{ eng.name }}</td></tr>
    <tr><td class="k">Status</td><td>{{ eng.status }}</td></tr>
    <tr><td class="k">Autonomy</td><td>{{ eng.autonomy }}</td></tr>
  </table>

  <h2>Scope &amp; Authorization</h2>
  <table class="meta">
    <tr><td class="k">Allowed domains</td><td>{{ scope.allow_domains | join(', ') or '—' }}</td></tr>
    <tr><td class="k">Allowed CIDRs</td><td>{{ scope.allow_cidrs | join(', ') or '—' }}</td></tr>
    <tr><td class="k">Deny list</td><td>{{ scope.deny_list | join(', ') or '—' }}</td></tr>
    <tr><td class="k">Action ceiling</td><td>{{ scope.max_action_class }}</td></tr>
    <tr><td class="k">Authorized by</td><td>{{ auth.by }}</td></tr>
    <tr><td class="k">Method</td><td>{{ auth.method }}</td></tr>
  </table>
  <p class="muted">Testing was authorized and confined to the scope above. Out-of-scope targets
  encountered during the run were denied and audited (see appendix).</p>

  <h2>Severity Summary</h2>
  <table class="tiles"><tr>
    {% for s in sev_order %}<td><div class="n" style="color:{{ colors[s] }}">{{ counts[s] }}</div>{{ s|capitalize }}</td>{% endfor %}
    <td><div class="n">{{ counts.total }}</div>Total</td>
  </tr></table>

  <h2>Methodology</h2>
  <p>Phases executed: {{ phases | join(' &rarr; ') or 'recon &rarr; scan &rarr; analyze' }}.
  {{ tool_runs }} tool invocations, each validated against scope before execution.</p>

  <h2>Findings ({{ findings|length }})</h2>
  {% if not findings %}<p class="muted">No findings recorded.</p>{% endif %}
  {% for f in findings %}
  <div class="finding" style="border-left-color:{{ colors[f.severity] }}">
    <span class="sev" style="background:{{ colors[f.severity] }}">{{ f.severity|upper }}</span>
    <strong>{{ f.title }}</strong>
    <div>{{ f.description }}</div>
    <div><span class="k">Asset:</span> {{ f.affected_asset }} &nbsp; <span class="k">Source:</span> {{ f.source }}</div>
    {% if f.cwe or f.cve or f.attack_techniques %}
    <div><span class="k">CWE:</span> {{ f.cwe or '—' }} &nbsp;
      <span class="k">CVE:</span> {{ f.cve | join(', ') or '—' }} &nbsp;
      <span class="k">ATT&amp;CK:</span> {{ f.attack_techniques | join(', ') or '—' }}</div>
    {% endif %}
    {% if f.remediation %}<div><span class="k">Remediation:</span> {{ f.remediation }}</div>{% endif %}
  </div>
  {% endfor %}

  <h2>Retest Checklist</h2>
  <ul>{% for f in findings %}<li>[ ] {{ f.title }} — {{ f.affected_asset }}</li>{% endfor %}
  {% if not findings %}<li class="muted">Nothing to retest.</li>{% endif %}</ul>

  <h2>Appendix</h2>
  <p><span class="k">Scope-denied targets:</span> {{ denied | join(', ') or 'none' }}</p>
  <p class="muted">Generated by HexaCore. Authorized penetration testing only.</p>
</body></html>""")


def _context(engagement, report) -> dict:
    scope = engagement.scope
    auth = engagement.authorization
    phases = [e.detail for e in report.events if e.type == "phase.changed"]
    tool_runs = sum(1 for e in report.events if e.type == "command.started")
    return {
        "eng": {"client": engagement.client, "name": engagement.name,
                "status": engagement.status.value, "autonomy": engagement.autonomy_profile},
        "scope": {"allow_domains": scope.allow_domains, "allow_cidrs": scope.allow_cidrs,
                  "deny_list": scope.deny_list, "max_action_class": scope.max_action_class.value},
        "auth": {"by": (f"{auth.authorizer_name} <{auth.authorizer_email}>" if auth else "—"),
                 "method": (auth.method.value if auth else "—")},
        "counts": report.counts.to_dict(),
        "sev_order": _SEV_ORDER, "colors": _SEV_COLOR,
        "findings": [f.to_dict() for f in report.findings],
        "phases": [p for p in phases if p], "tool_runs": tool_runs,
        "denied": sorted(set(report.denied_targets)),
    }


def build_html(engagement, report) -> str:
    return _HTML.render(**_context(engagement, report))


def build_pdf(engagement, report) -> bytes:
    from xhtml2pdf import pisa
    buf = io.BytesIO()
    pisa.CreatePDF(build_html(engagement, report), dest=buf, encoding="utf-8")
    return buf.getvalue()


def build_docx(engagement, report) -> bytes:
    from docx import Document
    ctx = _context(engagement, report)
    doc = Document()
    doc.add_heading(f"{ctx['eng']['client']} — Penetration Test Report", level=0)
    doc.add_paragraph(f"Engagement: {ctx['eng']['name']}  |  Status: {ctx['eng']['status']}"
                      f"  |  Autonomy: {ctx['eng']['autonomy']}")

    doc.add_heading("Scope & Authorization", level=1)
    s = ctx["scope"]
    for k, v in (("Allowed domains", s["allow_domains"]), ("Allowed CIDRs", s["allow_cidrs"]),
                 ("Deny list", s["deny_list"])):
        doc.add_paragraph(f"{k}: {', '.join(v) or '—'}")
    doc.add_paragraph(f"Action ceiling: {s['max_action_class']}")
    doc.add_paragraph(f"Authorized by: {ctx['auth']['by']} ({ctx['auth']['method']})")

    doc.add_heading("Severity Summary", level=1)
    c = ctx["counts"]
    doc.add_paragraph(" | ".join(f"{k.capitalize()}: {c[k]}" for k in _SEV_ORDER)
                      + f"  (Total: {c['total']})")

    doc.add_heading(f"Findings ({len(ctx['findings'])})", level=1)
    for f in ctx["findings"]:
        doc.add_heading(f"[{f['severity'].upper()}] {f['title']}", level=2)
        if f["description"]:
            doc.add_paragraph(f["description"])
        doc.add_paragraph(f"Asset: {f['affected_asset']}  |  Source: {f['source']}")
        doc.add_paragraph(f"CWE: {f['cwe'] or '—'}  |  CVE: {', '.join(f['cve']) or '—'}  |  "
                          f"ATT&CK: {', '.join(f['attack_techniques']) or '—'}")
        if f["remediation"]:
            doc.add_paragraph(f"Remediation: {f['remediation']}")

    doc.add_heading("Retest Checklist", level=1)
    for f in ctx["findings"]:
        doc.add_paragraph(f"{f['title']} — {f['affected_asset']}", style="List Bullet")

    doc.add_heading("Appendix", level=1)
    doc.add_paragraph(f"Scope-denied targets: {', '.join(ctx['denied']) or 'none'}")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def render(engagement, report, fmt: str = "html") -> "str | bytes":
    fmt = fmt.lower()
    if fmt == "html":
        return build_html(engagement, report)
    if fmt == "pdf":
        return build_pdf(engagement, report)
    if fmt == "docx":
        return build_docx(engagement, report)
    raise ValueError(f"unknown format {fmt!r} (html|pdf|docx)")
