apiVersion: v1
kind: Service
metadata:
  name: hexacore-api
spec:
  selector:
    app: hexacore-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hexacore-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hexacore.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hexacore-api
            port:
              number: 80
